# Copyright (c) 2024, Austin Brooks <ab.proxygen@outlook.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: linux-x64

on:
  workflow_call:
    inputs:
      target:
        description: 'Where assets should be published: artifact, nightly, release'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      target:
        description: 'Where assets should be published: artifact, nightly, release'
        type: string
        required: true
        default: artifact

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      actions: write

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Cancel forked repositories'
        if: ${{ github.repository_owner != 'square-0' }}
        run: |
          echo ERROR: Repository is a fork. Cancelling workflow...
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }} --interval 60
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Set environment variables'
        run: |
          pushd scripts/linux-x64
          ./env.sh
          popd

      - name: 'Build and package'
        run: |
          pushd scripts/linux-x64
          ./setup.sh
          ./comments.sh
          ./lint.sh
          ./l10n.sh
          ./ffmpeg.sh
          ./test.sh
          ./build.sh
          ./package.sh
          popd

          echo INFO: Upload target is ${{ inputs.target }}
          echo INFO: Tag ref is ${{ github.ref }}
          echo INFO: Tag ref_name is ${{ github.ref_name }}

          pushd release
          echo INFO: Files in the release folder...
          ls -al
          popd

      - name: 'Upload as an artifact'
        if: ${{ inputs.target == 'artifact' }}
        uses: actions/upload-artifact@v4
        with:
          name: proxygen-linux-x64
          path: release/*

      - name: 'Upload as a pre-release'
        if: ${{ inputs.target == 'nightly' }}
        run: |
          gh release upload nightly \
            release/* \
            --clobber \
            || exit 99
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Upload as a release'
        if: ${{ inputs.target == 'release' }}
        run: |
          gh release upload "${{ github.ref_name }}" \
            release/* \
            --clobber \
            || exit 99
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
