name: linux-x64-release

on:
  push:
    branches:
    - main
    tags: 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and package
        run: |
          cd scripts
          ./linux-x64-setup.sh
          ./linux-x64-lint.sh
          ./linux-x64-test.sh
          ./linux-x64-build.sh
          ./linux-x64-package.sh

      - name: Release binaries
        uses: actions/upload-artifact@v4
        with:
          name: proxygen-linux-x64
          path: |
            release/proxygen-linux-x64-*
