name: linux-x64-nightly

on:
  schedule:
    - cron: '22 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    if: ${{ github.repository_owner == 'square-0' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and package
        run: |
          cd scripts
          ./linux-x64-setup.sh
          ./linux-x64-lint.sh
          ./linux-x64-test.sh
          ./linux-x64-build.sh
          ./linux-x64-package.sh

      - name: Upload portable archive
        uses: actions/upload-artifact@v4
        with:
          name: proxygen-linux-x64-tgz
          path: |
            release/proxygen-linux-x64-*.tgz*

      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: proxygen-linux-x64-deb
          path: |
            release/proxygen-linux-x64-*.deb*
