name: proxygen-linux-x64-release

on:
  workflow_dispatch:
  schedule:
    - cron: '22 4 * * 0'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build and release
        run: |
          cd scripts
          ./linux-x64-setup.sh
          ./linux-x64-build.sh
          ./linux-x64-release.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: |
            release/proxygen-linux-x64-*.tgz

