# Copyright (c) 2024, Austin Brooks <ab.proxygen@outlook.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: linux-x64

on:
  workflow_call:
    inputs:
      TARGET:
        description: 'Where assets should be published: artifact, nightly, release'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      TARGET:
        description: 'Where assets should be published: artifact, nightly, release'
        type: string
        required: true
        default: 'artifact'

jobs:
  build:
    runs-on: ubuntu-20.04

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          pushd scripts
          ./linux-x64-env.sh
          popd
          # # Add pip's script directories to the PATH.
          # echo PATH="${PATH}:${HOME}/.local/bin" >> $GITHUB_ENV
          # # Prevent __pycache__ data from appearing in a packaged release.
          # echo PYTHONPYCACHEPREFIX="${HOME}/.cache/Python" >> $GITHUB_ENV
          # # The Python interpreter that all scripts should use.
          # echo PXG_PY_CMD="python3.12" >> $GITHUB_ENV

      # - name: Print environment variables
      #   run: |
      #     echo Environment variables set by \$GITHUB_ENV:
      #     echo PATH: ${PATH}
      #     echo PYTHONPYCACHEPREFIX: ${PYTHONPYCACHEPREFIX}
      #     echo PXG_PY_CMD: ${PXG_PY_CMD}

      - name: Build and package
        run: |
          pushd scripts
          ./linux-x64-setup.sh
          ./linux-x64-test.sh
          ./linux-x64-build.sh
          ./gettext-compile.sh
          ./linux-x64-package.sh
          ./cicd-changelog.sh
          popd

      - name: Upload as a pre-release
        if: ${{ github.event.inputs.TARGET == 'nightly' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          body_path: CHANGELOG-latest.md
          files: |
            release/proxygen-linux-x64-*.tgz*
            release/proxygen-linux-x64-*.deb*
          fail_on_unmatched_files: true
          # name: 'Nightly build'
          # prerelease: true
          # draft: false
            
      - name: Upload as a portable archive artifact
        if: ${{ github.event.inputs.TARGET == 'artifact' }}
        uses: actions/upload-artifact@v4
        with:
          name: proxygen-linux-x64-tgz
          path: release/proxygen-linux-x64-*.tgz*

      - name: Upload as a Debian package artifact
        if: ${{ github.event.inputs.TARGET == 'artifact' }}
        uses: actions/upload-artifact@v4
        with:
          name: proxygen-linux-x64-deb
          path: release/proxygen-linux-x64-*.deb*
