# Copyright (c) 2024, Austin Brooks <ab.proxygen@outlook.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: linux-x64

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and package
        run: |
          cd scripts
          ./linux-x64-setup.sh
          ./linux-x64-test.sh
          ./linux-x64-build.sh
          ./gettext-compile.sh
          ./linux-x64-package.sh

      - name: Upload portable archive
        uses: actions/upload-artifact@v4
        with:
          name: proxygen-linux-x64-tgz
          path: |
            release/proxygen-linux-x64-*.tgz*

      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: proxygen-linux-x64-deb
          path: |
            release/proxygen-linux-x64-*.deb*
