# Copyright (c) 2024, Austin Brooks <ab.proxygen@outlook.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: release

on:
  push:
    tags: ['v*']

permissions:
  contents: write
  actions: write

jobs:
  prepare:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        run: |
          echo INFO: Deleting release assets...
          gh release view "${{ github.ref_name }}" \
            --json assets \
            --jq '.assets[].name' | \
            while read -r line; do
                gh release delete-asset "${{ github.ref_name }}" "${line}" -y \
                  || (echo ERROR: Last command && exit 500)
            done

          echo INFO: Editing release details...
          ./scripts/cicd-changelog.sh "${{ github.ref }}"
          gh release edit "${{ github.ref_name }}" \
            --title "${{ github.ref_name }}" \
            --notes-file "release/CHANGELOG-release.md" \
            --latest \
            || (echo ERROR: Last command && exit 500)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  call-linux-x64:
    needs: [prepare]
    uses: ./.github/workflows/linux-x64.yml
    secrets: inherit
    with:
      target: release
